### PR TITLE
better documentation

### PR DESCRIPTION
**Pull request by WebReflection**
this both improve some inline documentation and the README, and fix typos in the test.

### CODE REVIEW

**Comment by pbuzdin** [comment]
Can you add something like jsbin-example, please?

**Comment by WebReflection** [comment]
@pbuzdin kinda weird comment on an already merged PR, but I like the idea: is there any specific example you would like to see live? I know "_my own things_" so that's what I test/develop for, but having a live example to showcase might be great for everyone else indeed.

**Comment by pbuzdin** [comment]
Sorry about discussing "here".

By example I mean just working in browser standalone HTML-page.

**Comment by WebReflection** [comment]
@pbuzdin this is literally the first line of the README:

Screenshot from 2020-03-07 18-28-12

This library is for rendering via NodeJS, not for browsers, check [uhtml](https://github.com/WebReflection/uhtml#readme) for browsers 😉

**Comment by pbuzdin** [comment]
Oh, then I mean working build :)

**Comment by WebReflection** [comment]
something like this?

```js
const {html} = require('ucontent');

require('http').createServer((req, res) => {
  res.writeHead(200, {'content-type': 'text/html'});
  res.end(html`
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ucontent</title>
  </head>
  <body>${html`
    <h1>Hello There</h1>
    <p>
      Thank you for visiting uhtml at ${new Date()}
    </p>
  `}</body>
  </html>`.min());
}).listen(8080);
```

**Comment by pbuzdin** [comment]
yes, but how to run this?

**Comment by WebReflection** [comment]
put that content in `test.js` then `node test.js`, after an `npm i ucontent` and visit http://localhost:8080/

**Comment by pbuzdin** [comment]
Now I see it working.

Thank you!

**Pull request merged**
